demo/_includes/footer.html
=> chore(ga): add GA

package.json, webpack.config.js
=> feat(env): add namespace

package.json
=> chore(pkg): change npm task

config/commit.template, config/validate-commit-msg.js, src/AnimationManager.ts, src/Axes.ts, src/AxesOption.ts, src/Coordinate.ts, src/InputObserver.ts, test/manual/js/index.js, test/unit/AnimationManager.spec.js, test/unit/AxisManager.spec.js, test/unit/Coordinate.spec.js
- improve animation performance
- remove `margin` option
- add `demo` commit style
=> For perf and etc

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore(.github): add github templates

declaration/inputType/PinchInput.d.ts, src/inputType/PinchInput.ts, test/unit/inputType/PanInput.spec.js, test/unit/inputType/PinchInput.spec.js
#45 
* changed offset value to return absolute unit
* added unit test
* fixed pan input test
=> fix(PinchInput): changed offset value to return absolute unit

src/Axes.ts, test/unit/Axes.spec.js
#55 
Made startPos parameter works synchronously
=> fix(Axes): apply startPos synchronously

src/Coordinate.ts
#41 
from #41,
> According to the unit test(https://goo.gl/G2kNn6), range param is given as [start, end] and
always start <end. therefore No need to iterate the algorithm in the return statement.
=> chore(Coordinate): simplify 'getInsidePosition'

src/Axes.ts, test/unit/Axes.spec.js
fix script error on disconnect  for unconnected
#61
=> fix(Axes): fix script error on disconnect  for unconnected

declaration/Axes.d.ts, declaration/inputType/MoveKeyInput.d.ts, demo/assets/js/axes.js, demo/demo.md, src/Axes.ts, src/inputType/MoveKeyInput.ts, src/inputType/WheelInput.ts, test/unit/inputType/MoveKeyInput.spec.js, test/unit/inputType/TestHeler.js
#64
Implemented `MoveKeyInput`.
* press down Move key(awsd and arrow keys) triggers change event.
* It provide deltas with two axes.
* If target element is not focused, the change event will not trigger.
=> feat(MoveKeyInput): implement move key input

declaration/utils.d.ts, package-lock.json, package.json, src/inputType/MoveKeyInput.ts, src/inputType/PinchInput.ts, src/utils.ts, test/manual/index.html, test/unit/utils.spec.js
#54
support IE8+ when using hammerjs-compatiable
=> fix(utils): support IE8 when using hammerjs-compatiable

declaration/AnimationManager.d.ts, declaration/Axes.d.ts, declaration/AxisManager.d.ts, src/AnimationManager.ts, src/Axes.ts, src/AxisManager.ts, src/InputObserver.ts, test/unit/AnimationManager.spec.js
- #3, #71 
- Animation grab not working
- Avoid cases where _complementaryOptions dropped.
ps. 
Next time, I will pull request as a jongmoon fork.
=> Support circular completely & Others

src/inputType/PanInput.ts, test/unit/inputType/PanInput.spec.js
=> fix(PanInput): prevent latent error

config/webpack.config.packaged.js, config/webpack.config.production.js
=> fix(webpack.config): fix index path

src/AxisManager.ts, test/unit/InputObserver.spec.js
=> fix(AxisManager): fix moveTo method for zero position

src/AnimationManager.ts, test/unit/AnimationManager.spec.js
call finish event when duration is 0
#120
=> fix(AnimationManager): call finish event

src/AnimationManager.ts, src/EventManager.ts, src/InputObserver.ts, test/manual/index.html, test/manual/js/index.js, test/unit/Axes.spec.js
Stop while change is in progress
#122
=> feat(Axes): add stop method in change event

src/AnimationManager.ts, src/AxisManager.ts, src/Coordinate.ts, src/EventManager.ts, src/InputObserver.ts, src/const.ts, src/utils.ts, test/unit/AnimationManager.spec.js, test/unit/AxisManager.spec.js, test/unit/InputObserver.spec.js, test/unit/utils.spec.js
=> fix: Fixed to handle the circular position

src/InputObserver.ts, test/unit/InputObserver.spec.js
=> fix(InputObserver): fix to save the destPos later

src/InputObserver.ts, test/unit/InputObserver.spec.js
=> fix(InputObserver): fix destPos for moveDistance

src/AnimationManager.ts, src/AxisManager.ts, src/utils.ts, test/unit/AnimationManager.spec.js, test/unit/Axes.spec.js
=>  fix: fix destPos for range changes dynamically

declaration/Axes.d.ts, declaration/index.d.ts, declaration/inputType/PanInput.d.ts, declaration/inputType/RotatePanInput.d.ts, src/Axes.ts, src/index.ts, src/index.umd.ts, src/inputType/PanInput.ts, src/inputType/RotatePanInput.ts, test/manual/js/rotate.js, test/manual/rotate.html, test/unit/inputType/RotatePanInput.spec.js, test/unit/inputType/TestHelper.js
=> feat: Add input type - RotatePanInput

packages/react/dist/Axes.js, packages/react/package.json, packages/react/src/Axes.js
=>  fix(react-axes): support fixed axis dynamically

src/AnimationManager.ts, src/Axes.ts
=>  fix: fix getDuration

src/AnimationManager.ts, test/unit/AnimationManager.spec.js
=> fix: fix destPos for floating point

src/Axes.ts, src/inputType/RotatePanInput.ts
=> docs: add link to round-option wiki

.editorconfig, README.md, package.json, src/browser.ts, src/const.ts, src/inputType/PanInput.ts, test/manual/edge.html, test/unit/Axes.spec.js
=> fix: fix ios safari edge and cancelable issue 

src/const.ts, src/inputType/PanInput.ts, test/unit/Axes.spec.js
=> feat: add iOSEdgeSwipeThreshold option #152

package-lock.json, package.json, src/const.ts
https://github.com/naver/egjs-agent/issues/33
=> fix: update @egjs/agent

package.json, packages/react/package-lock.json, rollup.config.js, src/Axes.ts, src/const.ts, src/eventInput/EventInput.ts, src/eventInput/MouseEventInput.ts, src/eventInput/PointerEventInput.ts, src/eventInput/TouchEventInput.ts, src/eventInput/TouchMouseEventInput.ts, src/inputType/InputType.ts, src/inputType/MoveKeyInput.ts, src/inputType/PanInput.ts, src/inputType/PinchInput.ts, src/inputType/RotatePanInput.ts, src/inputType/WheelInput.ts, src/types.ts, src/utils.ts
Incorrect #165 PR was closed and created a PR from a forked repository.
hammer.js dependency has removed from axes component, which was 45% size of bundle size.
hammerManagerOptions is no longer usable at input options.
size of axes.pkgd.js has reduced from 206kb to 127kb, axes.pkgd.min.js has reduced from 49kb to 35kb.
=> v3: remove hammerjs

package.json, src/EventManager.ts, src/inputType/MoveKeyInput.ts, src/inputType/PanInput.ts, src/inputType/RotatePanInput.ts, src/inputType/WheelInput.ts, src/types.ts
Updated @egjs/component to v3 which adds type inference when using events.
Also fixes type error occurring in legacy code, and resolve errors caused by recent merges.
=> v3: update @egjs/component to 3.0.1

demo/src/pages/demos/minimap.tsx, src/inputType/PanInput.ts, src/inputType/WheelInput.ts, src/utils.ts, test/unit/inputType/PanInput.spec.js, test/unit/inputType/TestHelper.js, test/unit/inputType/WheelInput.spec.js, test/unit/utils.spec.js
Implemented that WheelInput can support both vertical and horizontal mouse wheel connecting two axis to WheelInput
If WheelInput is connected to only one axis like `axes.connect("something1", new WheelInput("#area"));` as before, it connects the axis with the vertical wheel as before.
`axes.connect(["something1"], new WheelInput("#area"));` or `axes.connect("something1", new WheelInput("#area"));`
connects `something1` axis to the vertical mouse wheel.
`axes.connect(["", "something2"], new WheelInput("#area"));`
connects `something2` axis to the horizontal mouse wheel.
`axes.connect(["something1", "something2"], new WheelInput("#area"));`
connects `something1` axis to the vertical mouse wheel and connects `something2` axis to the horizontal mouse wheel.
You can check a …
=> feat: support horizintal mouse wheel at WheelInput

packages/axes/src/const.ts, packages/axes/src/eventInput/MouseEventInput.ts, packages/axes/src/eventInput/TouchMouseEventInput.ts, packages/axes/test/manual/cube.html, packages/axes/test/manual/js/cube.js, packages/axes/test/unit/inputType/InputType.spec.js
=> fix: fix wrong getTouches at TouchMouseEventInput

packages/axes/src/inputType/PanInput.ts, packages/axes/src/utils.ts, packages/axes/test/unit/inputType/PanInput.spec.js
=> fix: apply and revert styles when enables/disables PanInput

.github/workflows/run-unit.yml, packages/axes/README.md, packages/axes/src/eventInput/EventInput.ts, packages/axes/src/inputType/PanInput.ts, packages/axes/src/types.ts, packages/axes/test/unit/inputType/PanInput.spec.js, packages/axes/test/unit/inputType/TestHelper.js, packages/react-axes/README.md, packages/svelte-axes/README.md, packages/vue-axes/README.md, packages/vue2-axes/README.md
https://github.com/naver/egjs-axes/issues/221
=> fix: fix offset zero direction
