- src/animationHandler.js
- test/unit/MovableCoord.spec.js
Delay event after animation job is done.
Ref #5
#5
trigger `animationEnd` event after `_grab` operation has been done.
@sculove
> fix(animationHandler): delay 'animationEvent'.

- demo/assets/js/car360viewer.js
- demo/assets/js/cardinhand.js
- demo/assets/js/carousel.js
- demo/assets/js/cube.js
- demo/demo.md
- demo/started.md
- package.json
- src/Axes.ts
- src/inputType/HammerInput.ts
- src/inputType/InputType.ts
- test/manual/js/index.js
- test/unit/Axes.spec.js
- test/unit/HammerInput.spec.js
> feat(Axes): change 'mapInput' from

- declaration/inputType/WheelInput.d.ts
- src/inputType/WheelInput.ts
- test/unit/inputType/TestHeler.js
- test/unit/inputType/WheelInput.spec.js
#57 
debounce delay for release event is 50ms. (referened jQuery UI's scrollstop event)
> fix(WheelInput): make only release event debounced

- README.md
"http://naver.github.io/egjs/license.txt" doesn't exist. 
404 File not found
> docs(README): fix license error

- src/EventManager.ts
#76
Replace invalid variable `event` with `inputEvent` that are valid.
It makes firefox firing script error.
> fix(EventManager): replace invalid var to valid var

- src/AnimationManager.ts
- test/unit/Axes.spec.js
#78
`event` is not defined on Firefox.  event in option must be used.
> fix(AnimationManager): fix firefox script error

- declaration/inputType/PinchInput.d.ts
- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
#100
* remove PinchRecognizer from hammer manager when disconnecting PinchInput
* make PanInput destroy hammer manager only when one recognizer left.
> fix(PinchInput): remove PinchRecognizer from hammer manager when disconnecting PinchInput

- .gitignore
- package-lock.json
- src/inputType/PanInput.ts
- test/unit/inputType/PanInput.spec.js
#158 
This resolves #158 
Well, I actually tried to create a test code for this, but I couldn't reproduce it in our test env where scroll should happen with touch simulations.
I did a test on one of our demos(3d-carousel), and it worked fine.
The expected event order is `hold` -> `change` -> `release`
> feat: add releaseOnScroll option

- src/AnimationManager.ts
- src/InputObserver.ts
- src/inputType/InputType.ts
- src/inputType/MoveKeyInput.ts
- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
- src/inputType/RotatePanInput.ts
- src/inputType/WheelInput.ts
The logic that determines movement in a coordinate system is split in several pieces of code out of the AnimationManager. and all of them have been replaced to AnimationManager.
- When releasing pointer in range using PanInput, RotatePanInput. It moves coordinates by applying the deceleration option and speed obtained from the last input. Both logic calculates next offset at each InputType but it should be handled at AnimationManager since different animation types can have different next offset with same releasing velocity. 
- When holding pointer out of range within bounce area, it directly uses easing function from AnimationManager. Considering new animation types, it is necessary to calculate and return the result from AnimationManager rather than calling the easing function directly …
> v3: move animation calculation to AnimationManager

- src/inputType/MoveKeyInput.ts
When using MoveKeyInput within vertical, horizontal scroll. Arrow keys trigger scroll moving while focusing axes attached element. We can check this problem at [This Demo](https://naver.github.io/egjs-axes/assets/html/axes.html).
This PR fixes that issue by using `event.preventDefault()`.
> v3: fix movekeyinput scrolling

- src/EventManager.ts
- src/types.ts
Since the Axes event does not have a property associated with bounce ratio, current bounce ratio is calculated manually like [this demo](https://github.com/naver/egjs-axes/blob/master/demo/assets/js/pulltorefresh.js#L7-L13). 
This feature adds property about bounce ratio to onChange, onRelease for supporting actions associated with bounce.
> feat: add bounceRatio to onChange, onRelease

- package.json
- src/AnimationManager.ts
- src/AxisManager.ts
- src/EventManager.ts
- src/InputObserver.ts
- src/inputType/InputType.ts
- src/inputType/MoveKeyInput.ts
- src/inputType/PanInput.ts
- src/inputType/RotatePanInput.ts
- src/inputType/WheelInput.ts
- src/types.ts
When using WheelInput with mouse, offset of the virtual coordinate does not update smoothly.
This problem can be solved by using `animateTo` on change, and property named `releaseThreshold` has been added to `WheelInputOption` to trigger release event after animation ends.
`releaseThreshold` decides millisecond that trigger release event after last input. Before this property is added, Release event is automatically triggered after 50ms from last input.
> v3: support smooth WheeInput for mouse scrolling

- src/InputObserver.ts
- src/eventInput/EventInput.ts
- src/eventInput/TouchMouseEventInput.ts
- src/inputType/PanInput.ts
- src/inputType/RotatePanInput.ts
- test/manual/index.html
- test/manual/rotate.html
- test/unit/AnimationManager.spec.js
- test/unit/Axes.spec.js
- test/unit/AxisManager.spec.js
- test/unit/Coordinate.spec.js
- test/unit/InputObserver.spec.js
- test/unit/inputType/InputType.spec.js
- test/unit/inputType/MoveKeyInput.spec.js
- test/unit/inputType/PanInput.spec.js
- test/unit/inputType/PinchInput.spec.js
- test/unit/inputType/RotatePanInput.spec.js
- test/unit/inputType/WheelInput.spec.js
- test/unit/utils.spec.js
Unit test errors caused by recent changes have been fixed.
- Use newest method names in unit tests.
- Update WheelInput test for smooth WheelInput.
Codes that did not match the unit test's behavior have been fixed.
- Touch event by hammer simulator cannot be detected by `instanceof TouchEvent`, use `hasOwnProperty("touches")` instead.
- Some subsequent event at the test may have a deltaTime of zero. Calculate velocity to zero when deltaTime is 0.
- Fix invalid method names.
- [IOS Safari specific gesture](https://github.com/naver/egjs-axes/blob/master/src/inputType/PanInput.ts#L286-L320) was not working properly.
The remaining errors are as follows, and they will be fixed ASAP after v3 release.
- Test cases which uses `hammer.handlers["panstart"]` with sinon.
- Axes custom events not …
> v3: update unit tests

- src/EventManager.ts
- src/InputObserver.ts
- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
- src/utils.ts
- test/hammer-simulator.run.js
- test/unit/AnimationManager.spec.js
- test/unit/Axes.spec.js
- test/unit/AxisManager.spec.js
- test/unit/Coordinate.spec.js
- test/unit/InputObserver.spec.js
- test/unit/inputType/InputType.spec.js
- test/unit/inputType/MoveKeyInput.spec.js
- test/unit/inputType/PanInput.spec.js
- test/unit/inputType/PinchInput.spec.js
- test/unit/inputType/RotatePanInput.spec.js
- test/unit/inputType/TestHelper.js
- test/unit/inputType/WheelInput.spec.js
- test/unit/utils.spec.js
Fixed issues with unit tests not working correctly.
- Instead of tracking hammer events via sinon.spy, now track Axes events.
- An error that event.stop did not work properly was detected and fixed during the testing process.
Unit tests for `updateAnimation` and `stopAnimation` have been added.
> fix: correct unit tests with resolving event.stop bug

- .eslintrc.json
- demo/docs/demos/gallery.mdx
- demo/src/css/demos/cube.css
- demo/src/pages/demos/cube.tsx
- demo/src/pages/demos/subway.tsx
- src/const.ts
- src/eventInput/EventInput.ts
- src/eventInput/MouseEventInput.ts
- src/eventInput/PointerEventInput.ts
- src/eventInput/TouchEventInput.ts
- src/eventInput/TouchMouseEventInput.ts
- src/inputType/InputType.ts
- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
- src/inputType/RotatePanInput.ts
- src/types.ts
- test/unit/AnimationManager.spec.js
- test/unit/Axes.spec.js
- test/unit/AxisManager.spec.js
- test/unit/InputObserver.spec.js
- test/unit/inputType/InputType.spec.js
- test/unit/inputType/MoveKeyInput.spec.js
- test/unit/inputType/PanInput.spec.js
- test/unit/inputType/PinchInput.spec.js
- test/unit/inputType/RotatePanInput.spec.js
- test/unit/inputType/TestHelper.js
- test/unit/inputType/WheelInput.spec.js
- test/unit/utils.spec.js
Added inputButton to PanInputOption which used for PanInput and RotatePanInput.
inputButton option contains the types of mouse buttons PanInput and RotatePanInput will recognize.
inputButton option is ["left"] by default, you can configure like adding/changing it to "middle" and "right" .
Since every touch is recognized as a left click as the PointerEvent, every touch is recognized as a left click.
Added example of newly added option to the existing cube demo.
```ts
axes
.connect("rotateX rotateY", new PanInput(area, { inputButton: ["left"] ))
.connect("offsetX offsetY", new PanInput(area, { inputButton: ["right"] }));
```
- When naming this name, we used the singular name, just like the inputType option. If the name inputButton isn't appropriate for a list of mouse buttons that accept …
> feat: add inputButton option to PanInputOption

- src/Axes.ts
- src/EventManager.ts
- src/InputObserver.ts
- src/animation/AnimationManager.ts
- src/animation/EasingManager.ts
- src/const.ts
- src/eventInput/EventInput.ts
- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
- src/inputType/RotatePanInput.ts
- src/types.ts
- test/unit/AnimationManager.spec.js
Includes refactorings to improve readability and usability in other components.
In the past, the speed of coordinate change was calculated by comparing the [previous event with deltatime, x, and y.](https://github.com/naver/egjs-axes/blob/master/src/eventInput/EventInput.ts#L54-L58)
However when the deltaTime between events is very short, velocity is calculated abnormally high even for small coordinate changes.
It has been changed to update the speed only when the minimum time difference of VELOCITY_INTERVAL has been reached.
All code related to coordinate calculation through Easing has been separated into EasingManager.
AnimationManager is no longer holding information such as easing rates.
Now coordinates are calculated in other code, and it is convenient to add animations other than …
> fix: calculate velocity using interval, refactor AnimationManager

- src/eventInput/MouseEventInput.ts
- src/eventInput/PointerEventInput.ts
- src/eventInput/TouchEventInput.ts
- src/eventInput/TouchMouseEventInput.ts
In the test environment of other components using Axes, there are cases where pageX does not exist in the event.
This fix assumes that pageX and pageY don't always exist and changes to use clientX and clientY when calculating movement and delta.
> fix: use clientXY instead of pageXY for computing delta

- demo/src/css/demos/3dcarousel.css
- demo/src/css/demos/axes.css
- demo/src/css/demos/car360viewer.css
- demo/src/css/demos/cardinhand.css
- demo/src/css/demos/minimap.css
- demo/src/css/demos/subway.css
- demo/src/pages/demos/nestedaxes.tsx
- src/const.ts
- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
- src/utils.ts
- test/unit/inputType/PanInput.spec.js
- test/unit/inputType/PinchInput.spec.js
- test/unit/utils.spec.js
After we removed `hammerManagerOptions` In PanInput and PinchInput, the touch-action css property of the element is set to "none" to prevent scrolling when a touch event occurs. 
However, There are cases which should allow scrolling by touch entirely or only for a specific direction.
For example, [Flicking ](https://github.com/naver/egjs-flicking) that only moves horizontally should allow vertical scrolling via touch event. This provides usable option for [issue 637](https://github.com/naver/egjs-flicking/issues/673) on Flicking.
Also there are `useDrag` option at [conveyer](https://github.com/naver/egjs-conveyer/blob/main/packages/conveyer/src/Conveyer.ts#L427-L429) which set touch-action property to "auto".
Added `touchAction` options to PanInput and PinchInput so that we can set …
> feat: add touchAction option

- src/inputType/PanInput.ts
- src/inputType/PinchInput.ts
Fixed an error that remained in the iOS Safari environment in Axes 3.2.1.
You can check the [demo page](https://malangfox.github.io/egjs-flicking/Demos) that uses next version of Axes with this change applied.
Also Pan, Pinch input has changed so that if there is no inputType that fits the current device, it does not display an error and does not enable input.
Now the user interface designed to work only on the touch screen no longer displays an error when touch input is not possible.
> fix: PanInput not working in iOS Safari

- src/InputObserver.ts
- src/inputType/InputType.ts
- src/inputType/PanInput.ts
- src/inputType/WheelInput.ts
- test/manual/js/wheel.js
- test/manual/wheel.html
- test/unit/inputType/PanInput.spec.js
- test/unit/inputType/PinchInput.spec.js
- test/unit/inputType/WheelInput.spec.js
As #174 is applied, WheelInput always uses an animation to smooth out coordinate movement through the mouse wheel.
However, there are use cases where playing smooth animation is unnecessary and the coordinate change needs to be applied immediately.
This provides an option whether to use animation for the coordinate change of WheelInput.
> feat: add useAnimation option to WheelInput

- packages/axes/src/Axes.ts
- packages/axes/src/AxisManager.ts
- packages/axes/src/inputType/PanInput.ts
- packages/axes/test/unit/inputType/PanInput.spec.js
This adds a method `release` to stop and release the current input to `PanInput` and `RotatePanInput`.
Sometimes we need to cancel the current input that is occurring on a holdable InputType like `PanInput` .
For example, when using Flicking that includes PanInput, `moveTo` can occur while holding - ([check this comment.](https://github.com/naver/egjs-flicking/pull/711#discussion_r930561598))
`release` method can be used in cases like this.
> feat: add release to PanInput and RotatePanInput

- packages/axes/src/Axes.ts
- packages/axes/src/AxisManager.ts
- packages/axes/src/const.ts
- packages/axes/src/index.ts
- packages/axes/src/utils.ts
- packages/axes/test/unit/Axes.spec.js
Among the cases of using Axes, there is a case of directly changing the options of an Axes instance such like below.
```ts
...
const axes = this._axes!;
const axis = axes.axis[AXES.POSITION_KEY];
axis.circular = [controlParams.circular, controlParams.circular];
axis.range = [controlParams.range.min, controlParams.range.max];
axis.bounce = parseBounce(flicking.bounce, camera.size);
...
```
This add `setOptions` and `setAxis` methods to change the options related to the Axes instance to simplify use cases like this.
Changing `easing`, `interruptable` can be applied to an animation currently in progress.
Changing `maximumDuration`, `minimumDuration`, `deceleration` applies when calculating to play the animation on next time. If you want to change the remaining time of an animation that is …
> feat: add setOptions and setAxis method

- packages/axes/src/inputType/MoveKeyInput.ts
- packages/axes/src/inputType/PanInput.ts
- packages/axes/src/inputType/PinchInput.ts
- packages/axes/src/inputType/WheelInput.ts
- packages/axes/test/unit/inputType/PanInput.spec.js
This adds the option to cancel the [click](https://developer.mozilla.org/ko/docs/Web/API/Element/click_event) event when a valid drag occurs in `PanInput` and `RotatePanInput`.
We currently implemented this feature on [Flicking](https://naver.github.io/egjs-flicking/Options#preventclickondrag) that uses `PanInput`.
However, there are cases when you want to use this `preventClickOnDrag` feature in other UIs that uses `PanInput`.
After we add `preventClickOnDrag` to `PanInputOption`, Flicking can exclude implementation about `preventClickOnDrag` and handle it by `PanInputOption`.
> feat: add preventClickOnDrag option to PanInput

- packages/axes/package.json
- packages/axes/rollup.config.js
- packages/axes/src/index.cjs.ts
- packages/axes/src/inputType/PanInput.ts
- packages/axes/src/inputType/PinchInput.ts
- packages/axes/test/unit/inputType/PanInput.spec.js
- packages/axes/test/unit/inputType/PinchInput.spec.js
This fixes an issue that `threshold` option of `PanInput` and `PinchInput` did not work after the removal of the hammerjs dependency.
> fix: fix threshold option not working

- packages/axes/package.json
- packages/axes/src/const.ts
- packages/axes/src/eventInput/EventInput.ts
- packages/axes/src/eventInput/MouseEventInput.ts
- packages/axes/src/eventInput/PointerEventInput.ts
- packages/axes/src/eventInput/TouchEventInput.ts
- packages/axes/src/eventInput/TouchMouseEventInput.ts
- packages/axes/src/inputType/PanInput.ts
- packages/axes/src/inputType/RotatePanInput.ts
- packages/axes/src/inputType/WheelInput.ts
- packages/axes/test/unit/inputType/PanInput.spec.js
- packages/axes/test/unit/inputType/TestHelper.js
- packages/axes/test/unit/inputType/WheelInput.spec.js
- packages/demo/src/css/demos/logo.css
- packages/demo/src/pages/Options.mdx
- packages/demo/src/pages/demos/axesboard.tsx
- packages/demo/src/pages/demos/logo.tsx
This adds `InputKey` option that accepts input only when certain keys are pressed for the `PanInput` and `WheelInput`.
Considering that some devices don't have an Alt key and use a meta key instead, I implemented `InputKey` option to be an array of keys that allows input when any one of these is pressed.
> feat: add inputKey option to PanInput and WheelInput

- packages/axes/src/inputType/PanInput.ts
- packages/axes/test/unit/inputType/PanInput.spec.js
This fixes an error that `preventClickOnDrag` does not work properly when `panInput.options.preventClickOnDrag` changes to something different from the initial value.
> fix: fix preventClickOnDrag option not working when changed

- packages/axes/src/InputObserver.ts
- packages/axes/test/unit/InputObserver.spec.js
This fixes an error that abnormal bounce area appearing when the `circular` option was set to only one direction.
You can check this error with [demo](https://codepen.io/malangfox/pen/oNdmJKR) by moving the element to right side, which `circular` is `false`.
> fix: fix bounce occuring when circular is set in only one direction

- packages/axes/src/const.ts
- packages/axes/test/unit/utils.spec.js
This applies proper user-select styles for browsers that `user-select: none` is not available
> fix: add userSelect css props for non chrome browsers

- packages/react-axes/README.md
The method for defining event handlers for axes in '@egjs/react-axes' was not documented, so it has been added
> docs: Add event handler definition to react-axes readme.md

- packages/axes/src/inputType/PanInput.ts
- packages/axes/test/unit/AnimationManager.spec.js
- packages/axes/test/unit/inputType/PanInput.spec.js
Added code to prevent PanInput from being enabled in when there is no device available for input.
> fix: do not enable PanInput when there is no inputType
